name: CI Basic

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Print greeting
        run: echo "Hello from GitHub Actions!"

      - name: Example multi-line script
        run: |
          echo "Adicione aqui outras etapas de build,"
          echo "testes ou deploy para o seu projeto."
